---
- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: "19.04"
  name: repository

- src: https://github.com/open-io/ansible-role-openio-users.git
  version: "19.04"
  name: users

- src: https://github.com/open-io/ansible-role-openio-namespace.git
  version: "19.04"
  name: namespace

- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: "19.04"
  name: gridinit

- src: https://github.com/open-io/ansible-role-openio-conscience.git
  version: "19.04"
  name: conscience

...
