---
# Test playbook
- hosts: all
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: users
    - role: repository
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      openio_gridinit_per_ns: true
    - role: namespace
      openio_namespace_name: "{{ NS }}"
      openio_namespace_conscience_url: "{{ ansible_default_ipv4.address }}:6000"
      openio_namespace_zookeeper_url: ""
      openio_namespace_oioprxy_url: "{{ ansible_default_ipv4.address }}:6006"
      openio_namespace_event_agent_url: "beanstalk://{{ ansible_default_ipv4.address }}:6014"
      openio_namespace_ecd_url: "{{ ansible_default_ipv4.address }}:6017"
      openio_namespace_meta1_digits: 2
      openio_namespace_storage_policy: "THREECOPIES"
    - role: conscience
      openio_conscience_namespace: "{{ NS }}"
      openio_conscience_bind_address: "{{ ansible_default_ipv4.address }}"
      openio_conscience_pools: []
      openio_conscience_inventory_groupname: all
      openio_conscience_multiple: false
    - role: role_under_test
      openio_oioproxy_namespace: "{{ NS }}"
      openio_oioproxy_options:
        - proxy.cache.enabled=off
        - proxy.period.cs.downstream=7
...
